# Generated by Django 5.0.7 on 2024-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCRapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=20, unique=True)),
                ('nationality', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PassportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to='images/')),
                ('back_image', models.ImageField(upload_to='images/')),
                ('front_text', models.TextField(blank=True, null=True)),
                ('back_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OCRImage',
        ),
    ]
